apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h8gwlw0g6-go
  janus-idp.io/tekton: h8gwlw0g6-go
  backstage.io/kubernetes-id: h8gwlw0g6-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h8gwlw0g6-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
